management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8090
  tomcat:
    threads:
      max: 500

spring:
  main:
    #解决Bean重复定义问题
    allow-bean-definition-overriding: true
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        server-addr: 101.132.164.244:8888
        username: nacos
        password: ooad_javaee201
  servlet:
    multipart:
      #是否使用http上传
      enabled: true
      #最大请求文件的大小
      max-request-size: 10MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://101.132.164.244:3306/ooad?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF8
    username: dbuser
    password: 12345678
    druid:
      #初始化时建立物理连接的个数
      initial-size: 3
      #最小连接池数量
      min-idle: 3
      #最大连接池数量
      max-active: 10
      #获取连接时最大等待时间
      max-wait: 60000
      filter:
        stat:
          #是否开启慢sql查询监控
          log-slow-sql: true
          #慢SQL执行时间
          slow-sql-millis: 100
      validation-query: select 1
      #filters: config
      #connection-properties: config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALfa9QtUlD1QZNSn1jLCsWNFrLRph1leEdBk8oDYl2Fslsbvw+McsKLn3WYcY3Mue4litj+EsdUr+LO9dbt8MgMCAwEAAQ==

  redis:
    database: 0
    #Redis服务器地址
    host: 101.132.164.244
    #Redis服务器连接端口
    port: 6889
    # Redis服务器连接密码
    password: 123456
    #连接池最大连接数（使用负值表示没有限制）
    lettuce:
      pool:
        max-active: 100
        # 连接池中的最大空闲连接
        max-idle: 100
        # 连接池中的最小空闲连接
        min-idle: 0
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
    #连接超时时间（毫秒）
    timeout: 5000


mybatis:
  #po对象的包
  type-aliases-package: cn.edu.xmu.oomall.order.model.po
  #mapper.xml所在的位置
  mapper-locations: classpath*:cn.edu.xmu.oomall.order.mapper/*.xml
  #自动将SQL中查出来的带下划线的字段，转换为驼峰标志，再去匹配类中的属性
  configuration:
    #输出产生的SQL
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

#pagehelper分页插件配置
pagehelper:
  helper-dialect: mysql

rocketmq:
  # 指定namesrv地址
  name-server: 121.36.76.162:9876
  producer:
    #生产者group名称
    group: order-group-producer
    #一次发送多少数量消息
    max-message-size: 4096
    #发送消息超时时间,默认3000
    send-message-timeout: 3000
    #发送消息失败重试次数，默认2
    retry-times-when-send-async-failed: 2
  consumer:
    group: order-group-consumer

oomall:
  order:
    expiretime: 10000
    insert: insert-order
    #支付回调
    pay:
      common: PaymentMessage-0
      advance:
        deposit: PaymentMessage-2
        balance: PaymentMessage-3
    refund: RefundMessage-0

